name: "Update README"

on:
  push:
    branches:
      [ main , dev ]
  schedule:
    - cron: '12 */6 * * *'

jobs:
  Update:
    name: Update README
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configuration Python3
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          architecture: 'x64'

      - name: Configuration Environment
        run: pip3 install leancloud


      - name: Run update_README.md
        run: |
          cd .admin
          python3 update_README.py ${{ secrets.MasterKey }}

      - name: Commit changes
        uses: EndBug/add-and-commit@v5.2.0
        with:
          author_name: Lparksi
          author_email: l.moluan@outlook.com
          message: "Upload README"
          add: "*.md"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}